Seed: 42
Data:
    base_dir: "data/"
    train_batch_size: 64
    dropout: 0.2
    fusion: 1
    val_batch_size: 64
    test_batch_size: 64
    distributional: False
    num_classes: 10

Calibration:
    label_smoothing: True
    smoothing_param: 0.1
Optimization:
    lr: 0.002
    lr_schedule:
        name: 'StepLR'
        step_size: 5
        decay: 0.5
    patience: 20

Logger:
    save_dir: "results/"

Trainer:
    max_epochs: 300

